version: '3.8'

services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Configuração da aplicação Spring Boot
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-thymeleaf
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/thymeleaf
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin